#!/bin/bash

clear

# Define colors
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}"
echo "========================================="
echo "          Creating build directory       "
echo "========================================="
echo -e "${NC}"

mkdir -p build > /dev/null 2>&1
cd build > /dev/null 2>&1
rm -f monitor_exe > /dev/null 2>&1

echo -e "${GREEN}"
echo "========================================="
echo "         Compiling and Running...        "
echo "========================================="
echo -e "${NC}"

g++ -std=c++23 -Ofast -o monitor_exe ../monitor.cpp ../index.cpp ../util.cpp

./monitor_exe

cd - > /dev/null 2>&1
rm -rf build > /dev/null 2>&1

echo -e "${GREEN}"
echo "========================================="
echo " Build and Run is Done! Build directory  "
echo "               is removed.               "
echo "========================================="
echo -e "${NC}"