#!/bin/bash

clear

# Define colors
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Function to clean up and exit
cleanup() {
    echo -e "${GREEN}"
    echo "========================================="
    echo "          Cleaning up build directory    "
    echo "========================================="
    echo -e "${NC}"
    rm -rf build > /dev/null 2>&1
    exit 1
}

# Trap SIGINT (Ctrl+C) and SIGTSTP (Ctrl+Z) signals
trap cleanup SIGINT SIGTSTP

echo -e "${GREEN}"
echo "========================================="
echo "          Creating build directory       "
echo "========================================="
echo -e "${NC}"

rm -rf build > /dev/null 2>&1
mkdir -p build > /dev/null 2>&1
cd build > /dev/null 2>&1

echo -e "${GREEN}"
echo "========================================="
echo "         Compiling and Running...        "
echo "========================================="
echo -e "${NC}"

g++ -std=c++23 -Ofast -o monitor_exe ../monitor.cpp ../index.cpp ../util.cpp ../plat_id.cpp

./monitor_exe

cd - > /dev/null 2>&1
rm -rf build > /dev/null 2>&1

echo -e "${GREEN}"
echo "========================================="
echo " Build and Run is Done! Build directory  "
echo "               is removed.               "
echo "========================================="
echo -e "${NC}"

#TODO: echo "To create a ticket, visit: https://github.com/ol3h-unag1/stash_stellaris_saves/issues/new"
